[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "=0.10.0"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "0.2.15"

[[constraint]]
  name = "github.com/turnerlabs/harbor-auth-client"
  version = "1.1.0"

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "b7d6477501c13292d71fd3b8e688269e51b028ba"